#
# NOTE:
# - This is intended to be a `custom-values.yaml` starting point for non-production deployment (like minikube)

# External Dependencies:
# - A PUBLIC git repo for DAGs: ssh://git@repo.example.com:my-airflow-dags.git
#

###################################
# Airflow - Common Configs
###################################
airflow:
  ## the airflow executor type to use
  ##
  image:
    repository: renciorg/apache-airflow-1.10.14-python-3.8-git
    tag: latest
#  executor: CeleryExecutor
  executor: KubernetesExecutor

  ## the fernet key used to encrypt the connections in the database
  ##
  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="

  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    # Security
    AIRFLOW__CORE__SECURE_MODE: "True"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__WEBSERVER__RBAC: "False"
    AIRFLOW__KUBERNETES__GIT_REPO: "ssh://git@github.com/helxplatform/roger.git"
    # https://airflow.apache.org/docs/apache-airflow/1.10.12/configurations-ref.html#git-ssh-key-secret-name
    AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-secrets"
    # @TODO change this to master.
    AIRFLOW__KUBERNETES__GIT_BRANCH: "develop"
    AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
    AIRFLOW__KUBERNETES__GIT_SYNC_DEST: "roger"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "roger"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "TRUE"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "renciorg/roger-executor"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "0.26"
    # DAGS
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    ## Disable noisy "Handling signal: ttou" Gunicorn log messages
    GUNICORN_CMD_ARGS: "--log-level WARNING"

  extraPipPackages:
    - Babel==2.8.0
    - biolink-model==1.2.5
    - biolinkml==1.5.8
    - redisgraph==2.1.5
    - git+https://github.com/RedisGraph/redisgraph-bulk-loader.git
    - flatten-dict
    - git+https://github.com/stevencox/kgx.git
    ###################################
    # Volumes
    ###################################

    ## EXAMPLE:
    ##   extraVolumeMounts:
    ##     - name: synchronised-dags
    ##       mountPath: /opt/airflow/dags
    ##
  extraVolumeMounts:
    - name: roger-data
      mountPath: /dags/roger/data

    ## extra volumes for the web/scheduler/worker Pods
    ##
    ## EXAMPLE:
    ##   extraVolumes:
    ##     - name: synchronised-dags
    ##       emptyDir: {}
    ##
  extraVolumes:
    - name: roger-data
      emptyDir: {}

###################################
# Airflow - Scheduler Configs
###################################
scheduler:

  ## custom airflow connections for the airflow scheduler
  ##
#  connections:
#    - id: my_aws
#      type: aws
#      extra: |
#        {
#          "aws_access_key_id": "XXXXXXXXXXXXXXXXXXX",
#          "aws_secret_access_key": "XXXXXXXXXXXXXXX",
#          "region_name":"eu-central-1"
#        }

  ## custom airflow variables for the airflow scheduler
  ##
  variables: |
    { "environment": "dev" }

  ## custom airflow pools for the airflow scheduler
  ##
  pools: |
    {
      "example": {
        "description": "This is an example pool with 2 slots.",
        "slots": 2
      }
    }

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs for the Service of the web Pods
  ##
  service:
    type: NodePort

###################################
# Airflow - Worker Configs
###################################
workers:
  ## the number of workers Pods to run
  ##
  replicas: 1

###################################
# Airflow - DAGs Configs
###################################
dags:
  ## configs for the DAG git repository & sync container
  ##
  git:
    ## url of the git repository
    ##
    #url: "ssh://git@repo.example.com/my-airflow-dags.git"
    #url: "ssh://git@github.com/stevencox/airflow.git"
    url: "ssh://git@github.com/helxplatform/roger.git"
    
    ## the branch/tag/sha1 which we clone
    ##
    ref: redis-helm

    ## the name of a pre-created secret containing files for ~/.ssh/
    ##
    ## NOTE:
    ## - this is ONLY RELEVANT for SSH git repos
    ## - the secret commonly includes files: id_rsa, id_rsa.pub, known_hosts
    ## - known_hosts is NOT NEEDED if `git.sshKeyscan` is true
    ##
    secret: airflow-git-keys

    ## the name of the private key file in your `git.secret`
    ##
    ## NOTE:
    ## - this is ONLY RELEVANT for PRIVATE SSH git repos
    ##
    privateKeyName: id_rsa

    ## the host name of the git repo
    ##
    ## NOTE:
    ## - this is ONLY REQUIRED for SSH git repos
    ##
    ## EXAMPLE:
    ##   repoHost: "github.com"
    ##
    repoHost: "github.com"

    ## the port of the git repo
    ##
    ## NOTE:
    ## - this is ONLY REQUIRED for SSH git repos
    ##
    repoPort: 22

    ## configs for the git-sync container
    ##
    gitSync:
      ## enable the git-sync sidecar container
      ##
      enabled: true

      ## the git sync interval in seconds
      ##
      refreshTime: 60
  installRequirments: true

###################################
# Database - PostgreSQL Chart
###################################
postgresql:
  enabled: true

###################################
# Database - Redis Chart
###################################
redis:
  enabled: true
