apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elasticsearch
  name: elasticsearch
spec:
  containers:
  - env:
    - name: discovery.type
      value: single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    name: elasticsearch
    ports:
    - containerPort: 9200
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
