apiVersion: v1
kind: Service
metadata:
  name: {{ include "roger.fullname" . }}-tranql-service
  labels:
    {{- include "roger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tranql.service.type }}
  ports:
    - port: {{ .Values.tranql.port }}
      targetPort: {{ .Values.tranql.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "roger.selectorLabels" . | nindent 4 }}
    service-type: web-server